name: XanthHelp
version: '1.0-SNAPSHOT'
main: xanth.ogsammaenr.xanthHelp.XanthHelp
api-version: '1.21'

commands:
  yardım:
    description: "Yardım talebi oluşturmak için ana menüyü açar"
    usage: /yardım
  adminyardım:
    description: "Adminler için yardım taleplerini yönetme komudu"
    usage: /adminyardım
    permission: xanthhelp.adminhelp
  taleplerim:
    description: "yardım taleplerim"
    usage: /taleplerim
  ticketchat:
    description: "Ticket sohbetini açar"
    usage: /ticketchat

permissions:
  xanthhelp.adminhelp:
    description: "Admin komudu"
    default: op
